-- SELECT P.PRODUCT_CODE, (OSS.PRICEE * P.PRICE) 'TOTAL'
-- FROM PRODUCT P
-- JOIN (
--     SELECT OS.PRODUCT_ID, SUM(OS.SALES_AMOUNT) 'PRICEE'
--     FROM OFFLINE_SALE OS
--     GROUP BY OS.PRODUCT_ID
-- ) OSS ON P.PRODUCT_ID = OSS.PRODUCT_ID
-- ORDER BY 'TOTAL' DESC, P.PRODUCT_CODE ASC

SELECT P.PRODUCT_CODE, SUM(OS.SALES_AMOUNT * P.PRICE) PRICE
FROM OFFLINE_SALE OS
JOIN PRODUCT P ON OS.PRODUCT_ID = P.PRODUCT_ID
GROUP BY P.PRODUCT_CODE
ORDER BY PRICE DESC, P.PRODUCT_CODE ASC